
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false