AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

