AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'config/environments/**/*'
    - db/schema.rb
    - bin/bundle

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

